packaging_format = 2

id = "wekan"
name = "Wekan"
description.en = "Trello-like kanban"
description.fr = "Kanban similaire à Trello"

version = "6.80~ynh1"

maintainers = ["alexAubin", "ljf", "yalh76"]

[upstream]
license = "MIT"
website = "https://wekan.github.io"
demo = "https://demo.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h"
admindoc = "https://github.com/wekan/wekan/wiki"
code = "https://github.com/wekan/wekan"

[integration]
yunohost = ">= 11.1.16"
architectures = ["arm64", "amd64"]
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wekan"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/wekan/wekan/releases/download/v6.80/wekan-6.80-arm64.zip"
        arm64.sha256 = "f1b6865a5357391cb79cd9fa8c799542dcf38fea39503343540e9d705f2ea1b1"
        amd64.url = "https://github.com/wekan/wekan/releases/download/v6.80/wekan-6.80-amd64.zip"
        amd64.sha256 = "e1e627fc290deaa64ba1892cb7afcd34607300e150a9f365e5c39115c399bf16"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "*-amd64.zip"
        autoupdate.asset.arm64 = "*-arm64.zip"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
