packaging_format = 2

id = "wekan"
name = "Wekan"
description.en = "Trello-like kanban"
description.fr = "Kanban similaire à Trello"

version = "6.97~ynh1"

maintainers = ["alexAubin", "ljf", "yalh76"]

[upstream]
license = "MIT"
website = "https://wekan.github.io"
demo = "https://demo.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h"
admindoc = "https://github.com/wekan/wekan/wiki"
code = "https://github.com/wekan/wekan"

[integration]
yunohost = ">= 11.2"
architectures = ["arm64", "amd64"]
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wekan"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/wekan/wekan/releases/download/v7.09/wekan-7.09-arm64.zip"
        arm64.sha256 = "0ef14b07dd7fdb635b0350094f3df57aeb6d082e4525fe087e097c4f8cfbf238"
        amd64.url = "https://github.com/wekan/wekan/releases/download/v7.09/wekan-7.09-amd64.zip"
        amd64.sha256 = "7f9956c878bab40c99d5a7bebdeb1a7fa7d0016098cd47f0946bfde7d997ae7d"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "*-amd64.zip"
        autoupdate.asset.arm64 = "*-arm64.zip"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
